deploy_to_hosting:
  stage: deploy
  before_script:
    # Установка ssh-agent, если он не установлен
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    # Запуск ssh-agent
    - eval $(ssh-agent -s)
    # Добавление приватного SSH-ключа из переменной
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    # Пример команд, которые будут выполняться на вашем хостинге
    - ssh $SSH_USER@$SSH_HOST "cd /root/vkoridapiwrapper/; git pull origin main && dotnet publish -c Release -o ./publish && && chmod +x shs/add-service.sh && cd shs && ./add-service.sh"
  only:
    # Запускать пайплайн только для изменений в ветке 'main'
    - main