// <auto-generated />
using System;
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Data
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251010165809_AddVkOrdCacheEntities")]
    partial class AddVkOrdCacheEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApiCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Environment")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("Domain.Entities.DatabaseScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("ScriptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ScriptName")
                        .IsUnique();

                    b.ToTable("DatabaseScripts");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdContractCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ClientExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContractorExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Flags")
                        .HasColumnType("jsonb");

                    b.Property<bool>("HasAdditionalContracts")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LockedFields")
                        .HasColumnType("jsonb");

                    b.Property<string>("ParentContractExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("ParentContractId")
                        .HasColumnType("bigint");

                    b.Property<string>("Serial")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ClientExternalId");

                    b.HasIndex("ContractorExternalId");

                    b.HasIndex("Date");

                    b.HasIndex("DateEnd");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ParentContractId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("ApiCredentialId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdContractCache");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdContractParty", b =>
                {
                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("CounterpartyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VkOrdCounterpartyCacheId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractId", "CounterpartyId", "Role");

                    b.HasIndex("ContractId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Role");

                    b.HasIndex("VkOrdCounterpartyCacheId");

                    b.ToTable("VkOrdContractParty");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Inn")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("JuridicalDetails")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastUpdatedInVkOrd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Roles")
                        .HasColumnType("jsonb");

                    b.Property<string>("RsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Inn");

                    b.HasIndex("Name");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("ApiCredentialId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdCounterpartyCache");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCounterpartyRelation", b =>
                {
                    b.Property<long>("FromCounterpartyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToCounterpartyId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("FromCounterpartyId", "ToCounterpartyId", "RelationType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FromCounterpartyId");

                    b.HasIndex("RelationType");

                    b.HasIndex("ToCounterpartyId");

                    b.ToTable("VkOrdCounterpartyRelation");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Category")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Erid")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Flags")
                        .HasColumnType("jsonb");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kktus")
                        .HasColumnType("jsonb");

                    b.Property<string>("MediaExternalIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PersonExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUrls")
                        .HasColumnType("jsonb");

                    b.Property<string>("Targeting")
                        .HasColumnType("jsonb");

                    b.Property<string>("Texts")
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("Erid");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Name");

                    b.HasIndex("PersonExternalId");

                    b.HasIndex("Status");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("ApiCredentialId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdCreativeCache");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeContract", b =>
                {
                    b.Property<long>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CreativeId", "ContractId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreativeId");

                    b.ToTable("VkOrdCreativeContract");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeMedia", b =>
                {
                    b.Property<long>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("CreativeId", "MediaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreativeId");

                    b.HasIndex("MediaId");

                    b.HasIndex("Order");

                    b.ToTable("VkOrdCreativeMedia");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdMediaCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Filename")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MediaType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<string>("UploadStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("ContentType");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Filename");

                    b.HasIndex("MediaType");

                    b.HasIndex("Sha256");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UploadStatus");

                    b.HasIndex("ApiCredentialId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdMediaCache");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdStatisticsCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("AmountPerEvent")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreativeExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("DateEndActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEndPlanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateStartActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateStartPlanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("InvoiceShowsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PadExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Period")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<long>("ShowsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("StatisticsType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId");

                    b.HasIndex("CachedAt");

                    b.HasIndex("CreativeExternalId");

                    b.HasIndex("CreativeId");

                    b.HasIndex("DateEndActual");

                    b.HasIndex("DateEndPlanned");

                    b.HasIndex("DateStartActual");

                    b.HasIndex("DateStartPlanned");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PadExternalId");

                    b.HasIndex("Period");

                    b.HasIndex("StatisticsType");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("ApiCredentialId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdStatisticsCache");
                });

            modelBuilder.Entity("Domain.Entities.ApiCredential", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ApiCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdContractCache", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdContractCache", "ParentContract")
                        .WithMany("AdditionalContracts")
                        .HasForeignKey("ParentContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApiCredential");

                    b.Navigation("ParentContract");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdContractParty", b =>
                {
                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdContractCache", "Contract")
                        .WithMany("ContractParties")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", "Counterparty")
                        .WithMany("ClientContracts")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", null)
                        .WithMany("ContractorContracts")
                        .HasForeignKey("VkOrdCounterpartyCacheId");

                    b.Navigation("Contract");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCounterpartyRelation", b =>
                {
                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", "FromCounterparty")
                        .WithMany("Relations")
                        .HasForeignKey("FromCounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", "ToCounterparty")
                        .WithMany()
                        .HasForeignKey("ToCounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCounterparty");

                    b.Navigation("ToCounterparty");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeCache", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeContract", b =>
                {
                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdContractCache", "Contract")
                        .WithMany("CreativeContracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCreativeCache", "Creative")
                        .WithMany("CreativeContracts")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeMedia", b =>
                {
                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCreativeCache", "Creative")
                        .WithMany("CreativeMedia")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdMediaCache", "Media")
                        .WithMany("CreativeMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdMediaCache", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdStatisticsCache", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany()
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrdCache.VkOrdCreativeCache", "Creative")
                        .WithMany("Statistics")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ApiCredential");

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ApiCredentials");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdContractCache", b =>
                {
                    b.Navigation("AdditionalContracts");

                    b.Navigation("ContractParties");

                    b.Navigation("CreativeContracts");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCounterpartyCache", b =>
                {
                    b.Navigation("ClientContracts");

                    b.Navigation("ContractorContracts");

                    b.Navigation("Relations");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdCreativeCache", b =>
                {
                    b.Navigation("CreativeContracts");

                    b.Navigation("CreativeMedia");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Domain.Entities.VkOrdCache.VkOrdMediaCache", b =>
                {
                    b.Navigation("CreativeMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
