// <auto-generated />
using System;
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019095728_AddFlowTemplatesTable")]
    partial class AddFlowTemplatesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApiCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiEnvironment")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiCredentials");
                });

            modelBuilder.Entity("Domain.Entities.DatabaseScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<string>("ScriptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScriptName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ScriptName")
                        .IsUnique();

                    b.ToTable("DatabaseScripts");
                });

            modelBuilder.Entity("Domain.Entities.FlowTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiCredentialId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiCredentialId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("CreatedAt")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("Name")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Type")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("UseCount")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ApiCredentialId", "IsActive")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("ApiCredentialId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("FlowTemplates");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long?>("VkOrdContractId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("VkOrdContractId");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdContracts");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdContractParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<long>("CounterpartyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("CounterpartyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Role");

                    b.HasIndex("ContractId", "CounterpartyId", "Role");

                    b.ToTable("VkOrdContractParties");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCounterparty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdCounterparties");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreative", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdCreatives");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreativeContract", b =>
                {
                    b.Property<long>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CreativeId", "ContractId");

                    b.HasIndex("ContractId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreativeId");

                    b.ToTable("VkOrdCreativeContract");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreativeMedia", b =>
                {
                    b.Property<long>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<long>("MediaId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("CreativeId", "MediaId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreativeId");

                    b.HasIndex("MediaId");

                    b.HasIndex("Order");

                    b.ToTable("VkOrdCreativeMedia");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdInvoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContractExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ContractExternalId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsDraft");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("LogicalAccountId", "ContractExternalId");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdInvoices");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdLogicalAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("VkLogicalAccounts");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdMedias");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("AmountPerEvent")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreativeExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("CreativeId")
                        .HasColumnType("bigint");

                    b.Property<string>("DataHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("DateEndActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEndPlanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateStartActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateStartPlanned")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("InvoiceShowsCount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("LogicalAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("PadExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PayType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Period")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<long>("ShowsCount")
                        .HasColumnType("bigint");

                    b.Property<string>("StatisticsType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreativeExternalId");

                    b.HasIndex("CreativeId");

                    b.HasIndex("DateEndActual");

                    b.HasIndex("DateEndPlanned");

                    b.HasIndex("DateStartActual");

                    b.HasIndex("DateStartPlanned");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("LogicalAccountId");

                    b.HasIndex("PadExternalId");

                    b.HasIndex("Period");

                    b.HasIndex("StatisticsType");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("LogicalAccountId", "ExternalId")
                        .IsUnique();

                    b.ToTable("VkOrdStatistics");
                });

            modelBuilder.Entity("Domain.Entities.ApiCredential", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "LogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ApiCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogicalAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.FlowTemplate", b =>
                {
                    b.HasOne("Domain.Entities.ApiCredential", "ApiCredential")
                        .WithMany("FlowTemplates")
                        .HasForeignKey("ApiCredentialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiCredential");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdContract", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrd.VkOrdContract", null)
                        .WithMany("AdditionalContracts")
                        .HasForeignKey("VkOrdContractId");

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdContractParty", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdContract", "Contract")
                        .WithMany("ContractParties")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrd.VkOrdCounterparty", "Counterparty")
                        .WithMany("ContractParties")
                        .HasForeignKey("CounterpartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Counterparty");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCounterparty", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreative", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreativeContract", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdContract", "Contract")
                        .WithMany("CreativeContracts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrd.VkOrdCreative", "Creative")
                        .WithMany("CreativeContracts")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Creative");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreativeMedia", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdCreative", "Creative")
                        .WithMany("CreativeMedia")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrd.VkOrdMedia", "Media")
                        .WithMany("CreativeMedia")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdInvoice", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VkOrd.VkOrdContract", "Contract")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId", "ContractExternalId")
                        .HasPrincipalKey("LogicalAccountId", "ExternalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdMedia", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdStatistic", b =>
                {
                    b.HasOne("Domain.Entities.VkOrd.VkOrdCreative", "Creative")
                        .WithMany("Statistics")
                        .HasForeignKey("CreativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.VkOrd.VkOrdLogicalAccount", "OrdLogicalAccount")
                        .WithMany()
                        .HasForeignKey("LogicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creative");

                    b.Navigation("OrdLogicalAccount");
                });

            modelBuilder.Entity("Domain.Entities.ApiCredential", b =>
                {
                    b.Navigation("FlowTemplates");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ApiCredentials");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdContract", b =>
                {
                    b.Navigation("AdditionalContracts");

                    b.Navigation("ContractParties");

                    b.Navigation("CreativeContracts");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCounterparty", b =>
                {
                    b.Navigation("ContractParties");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdCreative", b =>
                {
                    b.Navigation("CreativeContracts");

                    b.Navigation("CreativeMedia");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Domain.Entities.VkOrd.VkOrdMedia", b =>
                {
                    b.Navigation("CreativeMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
