START TRANSACTION;

DELETE FROM "ApiCredentials";
DELETE FROM "RefreshTokens";
DELETE FROM "Users";

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "Users" ALTER COLUMN "RowVersion" SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" DROP CONSTRAINT "FK_ApiCredentials_Users_UserId";
    ALTER TABLE "RefreshTokens" DROP CONSTRAINT "FK_RefreshTokens_Users_UserId";
    ALTER TABLE "Users" DROP COLUMN "Id";
    ALTER TABLE "Users" ADD COLUMN "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "Users" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "Users" ADD "PublicId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" DROP COLUMN "UserId";
    ALTER TABLE "RefreshTokens" ADD COLUMN "UserId" bigint NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" DROP COLUMN "Id";
    ALTER TABLE "RefreshTokens" ADD COLUMN "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" ADD "PublicId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" ADD "RowVersion" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "RefreshTokens" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "DatabaseScripts" ALTER COLUMN "ErrorMessage" TYPE text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" DROP COLUMN "UserId";
    ALTER TABLE "ApiCredentials" ADD COLUMN "UserId" bigint NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" ALTER COLUMN "RowVersion" SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" ALTER COLUMN "Environment" TYPE integer USING "Environment"::integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" DROP COLUMN "Id";
    ALTER TABLE "ApiCredentials" ADD COLUMN "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" ADD "IsDeleted" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" ADD "PublicId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    ALTER TABLE "ApiCredentials" ADD CONSTRAINT "FK_ApiCredentials_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    ALTER TABLE "RefreshTokens" ADD CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    CREATE UNIQUE INDEX "IX_Users_PublicId" ON "Users" ("PublicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_PublicId" ON "RefreshTokens" ("PublicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    CREATE UNIQUE INDEX "IX_ApiCredentials_PublicId" ON "ApiCredentials" ("PublicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251005110620_RefactoringEntityBaseWithExtensions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251005110620_RefactoringEntityBaseWithExtensions', '8.0.10');
    END IF;
END $EF$;
COMMIT;

