START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdContractCache" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Type" character varying(50),
        "ClientExternalId" character varying(255),
        "ContractorExternalId" character varying(255),
        "ActionType" character varying(50),
        "SubjectType" character varying(50),
        "Date" timestamp with time zone,
        "DateEnd" timestamp with time zone,
        "Serial" character varying(255),
        "Flags" jsonb,
        "ParentContractExternalId" character varying(255),
        "ParentContractId" bigint,
        "Amount" numeric(18,2),
        "HasAdditionalContracts" boolean NOT NULL,
        "Cid" character varying(255),
        "LockedFields" jsonb,
        "CreateDate" timestamp with time zone,
        "SyncStatus" integer NOT NULL,
        "ApiCredentialId" bigint NOT NULL,
        "ExternalId" character varying(255) NOT NULL,
        "CachedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Version" integer NOT NULL,
        "JsonData" jsonb NOT NULL,
        "DataHash" character varying(64),
        CONSTRAINT "PK_VkOrdContractCache" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VkOrdContractCache_ApiCredentials_ApiCredentialId" FOREIGN KEY ("ApiCredentialId") REFERENCES "ApiCredentials" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdContractCache_VkOrdContractCache_ParentContractId" FOREIGN KEY ("ParentContractId") REFERENCES "VkOrdContractCache" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdCounterpartyCache" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Inn" character varying(12),
        "Name" character varying(500),
        "RsUrl" character varying(500),
        "Roles" jsonb,
        "JuridicalDetails" jsonb,
        "LastUpdatedInVkOrd" timestamp with time zone,
        "SyncStatus" integer NOT NULL,
        "ApiCredentialId" bigint NOT NULL,
        "ExternalId" character varying(255) NOT NULL,
        "CachedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Version" integer NOT NULL,
        "JsonData" jsonb NOT NULL,
        "DataHash" character varying(64),
        CONSTRAINT "PK_VkOrdCounterpartyCache" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VkOrdCounterpartyCache_ApiCredentials_ApiCredentialId" FOREIGN KEY ("ApiCredentialId") REFERENCES "ApiCredentials" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdCreativeCache" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Erid" character varying(255),
        "PersonExternalId" character varying(255),
        "Kktus" jsonb,
        "Name" character varying(255),
        "Brand" character varying(255),
        "Category" character varying(255),
        "Description" character varying(2000),
        "PayType" character varying(50),
        "Form" character varying(50),
        "Targeting" jsonb,
        "TargetUrls" jsonb,
        "Texts" jsonb,
        "MediaExternalIds" jsonb,
        "Flags" jsonb,
        "Status" character varying(50),
        "SyncStatus" integer NOT NULL,
        "ApiCredentialId" bigint NOT NULL,
        "ExternalId" character varying(255) NOT NULL,
        "CachedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Version" integer NOT NULL,
        "JsonData" jsonb NOT NULL,
        "DataHash" character varying(64),
        CONSTRAINT "PK_VkOrdCreativeCache" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VkOrdCreativeCache_ApiCredentials_ApiCredentialId" FOREIGN KEY ("ApiCredentialId") REFERENCES "ApiCredentials" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdMediaCache" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Filename" character varying(500),
        "Sha256" character varying(64),
        "CreateDate" timestamp with time zone,
        "Size" bigint NOT NULL,
        "ContentType" character varying(100),
        "Description" character varying(1000),
        "MediaType" character varying(50),
        "DownloadUrl" character varying(1000),
        "UploadStatus" character varying(50),
        "SyncStatus" integer NOT NULL,
        "ApiCredentialId" bigint NOT NULL,
        "ExternalId" character varying(255) NOT NULL,
        "CachedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Version" integer NOT NULL,
        "JsonData" jsonb NOT NULL,
        "DataHash" character varying(64),
        CONSTRAINT "PK_VkOrdMediaCache" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VkOrdMediaCache_ApiCredentials_ApiCredentialId" FOREIGN KEY ("ApiCredentialId") REFERENCES "ApiCredentials" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdContractParty" (
        "ContractId" bigint NOT NULL,
        "CounterpartyId" bigint NOT NULL,
        "Role" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "VkOrdCounterpartyCacheId" bigint,
        CONSTRAINT "PK_VkOrdContractParty" PRIMARY KEY ("ContractId", "CounterpartyId", "Role"),
        CONSTRAINT "FK_VkOrdContractParty_VkOrdContractCache_ContractId" FOREIGN KEY ("ContractId") REFERENCES "VkOrdContractCache" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdContractParty_VkOrdCounterpartyCache_CounterpartyId" FOREIGN KEY ("CounterpartyId") REFERENCES "VkOrdCounterpartyCache" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdContractParty_VkOrdCounterpartyCache_VkOrdCounterparty~" FOREIGN KEY ("VkOrdCounterpartyCacheId") REFERENCES "VkOrdCounterpartyCache" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdCounterpartyRelation" (
        "FromCounterpartyId" bigint NOT NULL,
        "ToCounterpartyId" bigint NOT NULL,
        "RelationType" character varying(50) NOT NULL,
        "Description" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VkOrdCounterpartyRelation" PRIMARY KEY ("FromCounterpartyId", "ToCounterpartyId", "RelationType"),
        CONSTRAINT "FK_VkOrdCounterpartyRelation_VkOrdCounterpartyCache_FromCounte~" FOREIGN KEY ("FromCounterpartyId") REFERENCES "VkOrdCounterpartyCache" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdCounterpartyRelation_VkOrdCounterpartyCache_ToCounterp~" FOREIGN KEY ("ToCounterpartyId") REFERENCES "VkOrdCounterpartyCache" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdCreativeContract" (
        "CreativeId" bigint NOT NULL,
        "ContractId" bigint NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VkOrdCreativeContract" PRIMARY KEY ("CreativeId", "ContractId"),
        CONSTRAINT "FK_VkOrdCreativeContract_VkOrdContractCache_ContractId" FOREIGN KEY ("ContractId") REFERENCES "VkOrdContractCache" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdCreativeContract_VkOrdCreativeCache_CreativeId" FOREIGN KEY ("CreativeId") REFERENCES "VkOrdCreativeCache" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdStatisticsCache" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CreativeExternalId" character varying(255) NOT NULL,
        "CreativeId" bigint,
        "PadExternalId" character varying(255) NOT NULL,
        "ShowsCount" bigint NOT NULL,
        "InvoiceShowsCount" bigint NOT NULL,
        "Amount" jsonb,
        "AmountPerEvent" numeric(18,8) NOT NULL,
        "PayType" character varying(50),
        "DateStartPlanned" timestamp with time zone,
        "DateEndPlanned" timestamp with time zone,
        "DateStartActual" timestamp with time zone,
        "DateEndActual" timestamp with time zone,
        "Period" character varying(7),
        "StatisticsType" character varying(50),
        "SyncStatus" integer NOT NULL,
        "ApiCredentialId" bigint NOT NULL,
        "ExternalId" character varying(255) NOT NULL,
        "CachedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "Version" integer NOT NULL,
        "JsonData" jsonb NOT NULL,
        "DataHash" character varying(64),
        CONSTRAINT "PK_VkOrdStatisticsCache" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VkOrdStatisticsCache_ApiCredentials_ApiCredentialId" FOREIGN KEY ("ApiCredentialId") REFERENCES "ApiCredentials" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdStatisticsCache_VkOrdCreativeCache_CreativeId" FOREIGN KEY ("CreativeId") REFERENCES "VkOrdCreativeCache" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE TABLE "VkOrdCreativeMedia" (
        "CreativeId" bigint NOT NULL,
        "MediaId" bigint NOT NULL,
        "Order" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VkOrdCreativeMedia" PRIMARY KEY ("CreativeId", "MediaId"),
        CONSTRAINT "FK_VkOrdCreativeMedia_VkOrdCreativeCache_CreativeId" FOREIGN KEY ("CreativeId") REFERENCES "VkOrdCreativeCache" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VkOrdCreativeMedia_VkOrdMediaCache_MediaId" FOREIGN KEY ("MediaId") REFERENCES "VkOrdMediaCache" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_ApiCredentialId" ON "VkOrdContractCache" ("ApiCredentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE UNIQUE INDEX "IX_VkOrdContractCache_ApiCredentialId_ExternalId" ON "VkOrdContractCache" ("ApiCredentialId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_CachedAt" ON "VkOrdContractCache" ("CachedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_ClientExternalId" ON "VkOrdContractCache" ("ClientExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_ContractorExternalId" ON "VkOrdContractCache" ("ContractorExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_Date" ON "VkOrdContractCache" ("Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_DateEnd" ON "VkOrdContractCache" ("DateEnd");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_ExpiresAt" ON "VkOrdContractCache" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_ParentContractId" ON "VkOrdContractCache" ("ParentContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractCache_SyncStatus" ON "VkOrdContractCache" ("SyncStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractParty_ContractId" ON "VkOrdContractParty" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractParty_CounterpartyId" ON "VkOrdContractParty" ("CounterpartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractParty_CreatedAt" ON "VkOrdContractParty" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractParty_Role" ON "VkOrdContractParty" ("Role");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdContractParty_VkOrdCounterpartyCacheId" ON "VkOrdContractParty" ("VkOrdCounterpartyCacheId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_ApiCredentialId" ON "VkOrdCounterpartyCache" ("ApiCredentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE UNIQUE INDEX "IX_VkOrdCounterpartyCache_ApiCredentialId_ExternalId" ON "VkOrdCounterpartyCache" ("ApiCredentialId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_CachedAt" ON "VkOrdCounterpartyCache" ("CachedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_ExpiresAt" ON "VkOrdCounterpartyCache" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_Inn" ON "VkOrdCounterpartyCache" ("Inn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_Name" ON "VkOrdCounterpartyCache" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyCache_SyncStatus" ON "VkOrdCounterpartyCache" ("SyncStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyRelation_CreatedAt" ON "VkOrdCounterpartyRelation" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyRelation_FromCounterpartyId" ON "VkOrdCounterpartyRelation" ("FromCounterpartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyRelation_RelationType" ON "VkOrdCounterpartyRelation" ("RelationType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCounterpartyRelation_ToCounterpartyId" ON "VkOrdCounterpartyRelation" ("ToCounterpartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_ApiCredentialId" ON "VkOrdCreativeCache" ("ApiCredentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE UNIQUE INDEX "IX_VkOrdCreativeCache_ApiCredentialId_ExternalId" ON "VkOrdCreativeCache" ("ApiCredentialId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_CachedAt" ON "VkOrdCreativeCache" ("CachedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_Erid" ON "VkOrdCreativeCache" ("Erid");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_ExpiresAt" ON "VkOrdCreativeCache" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_Name" ON "VkOrdCreativeCache" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_PersonExternalId" ON "VkOrdCreativeCache" ("PersonExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_Status" ON "VkOrdCreativeCache" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeCache_SyncStatus" ON "VkOrdCreativeCache" ("SyncStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeContract_ContractId" ON "VkOrdCreativeContract" ("ContractId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeContract_CreatedAt" ON "VkOrdCreativeContract" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeContract_CreativeId" ON "VkOrdCreativeContract" ("CreativeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeMedia_CreatedAt" ON "VkOrdCreativeMedia" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeMedia_CreativeId" ON "VkOrdCreativeMedia" ("CreativeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeMedia_MediaId" ON "VkOrdCreativeMedia" ("MediaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdCreativeMedia_Order" ON "VkOrdCreativeMedia" ("Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_ApiCredentialId" ON "VkOrdMediaCache" ("ApiCredentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE UNIQUE INDEX "IX_VkOrdMediaCache_ApiCredentialId_ExternalId" ON "VkOrdMediaCache" ("ApiCredentialId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_CachedAt" ON "VkOrdMediaCache" ("CachedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_ContentType" ON "VkOrdMediaCache" ("ContentType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_ExpiresAt" ON "VkOrdMediaCache" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_Filename" ON "VkOrdMediaCache" ("Filename");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_MediaType" ON "VkOrdMediaCache" ("MediaType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_Sha256" ON "VkOrdMediaCache" ("Sha256");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_SyncStatus" ON "VkOrdMediaCache" ("SyncStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdMediaCache_UploadStatus" ON "VkOrdMediaCache" ("UploadStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_ApiCredentialId" ON "VkOrdStatisticsCache" ("ApiCredentialId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE UNIQUE INDEX "IX_VkOrdStatisticsCache_ApiCredentialId_ExternalId" ON "VkOrdStatisticsCache" ("ApiCredentialId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_CachedAt" ON "VkOrdStatisticsCache" ("CachedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_CreativeExternalId" ON "VkOrdStatisticsCache" ("CreativeExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_CreativeId" ON "VkOrdStatisticsCache" ("CreativeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_DateEndActual" ON "VkOrdStatisticsCache" ("DateEndActual");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_DateEndPlanned" ON "VkOrdStatisticsCache" ("DateEndPlanned");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_DateStartActual" ON "VkOrdStatisticsCache" ("DateStartActual");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_DateStartPlanned" ON "VkOrdStatisticsCache" ("DateStartPlanned");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_ExpiresAt" ON "VkOrdStatisticsCache" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_PadExternalId" ON "VkOrdStatisticsCache" ("PadExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_Period" ON "VkOrdStatisticsCache" ("Period");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_StatisticsType" ON "VkOrdStatisticsCache" ("StatisticsType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    CREATE INDEX "IX_VkOrdStatisticsCache_SyncStatus" ON "VkOrdStatisticsCache" ("SyncStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010165809_AddVkOrdCacheEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251010165809_AddVkOrdCacheEntities', '8.0.10');
    END IF;
END $EF$;
COMMIT;

